# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
