# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodplan',
            old_name='food_list',
            new_name='days',
        ),
    ]
