# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0002_auto_20160711_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplan',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 7, 11, 16, 41, 19, 106590, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
