# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0003_auto_20160305_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='categories',
        ),
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='foodroller.Category'),
        ),
    ]
