# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0004_auto_20160305_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='categories',
        ),
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.ManyToManyField(related_name='food', to='foodroller.Category'),
        ),
    ]
