# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0004_auto_20151220_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='last_cooked',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
