# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0005_auto_20151220_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='foodroller.Ingredient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='last_cooked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
