# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0006_auto_20160307_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
