# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0006_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='duration',
            field=models.CharField(blank=True, choices=[('30min', '< 30 min'), ('1hr', '< 1 h'), ('2hr', '< 2 h'), ('2hr+', '> 2 h')], max_length=5, null=True),
        ),
    ]
