# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0009_auto_20160102_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='categories',
        ),
    ]
