# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0010_auto_20160102_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(null=True, upload_to='media/img'),
        ),
    ]
