# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0011_food_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='thumb',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
