# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0013_auto_20160108_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='thumb',
        ),
    ]
