# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:24
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0013_auto_20160103_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='img'),
        ),
    ]
