# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodroller', '0014_auto_20160103_2024'),
        ('foodroller', '0015_food_slug'),
    ]

    operations = [
    ]
